/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ud;

import javax.swing.JOptionPane;
import modal.bean.Usuario;
import modal.dao.UsuarioDAO;

/**
 *
 * @author mathe
 */
public class UpdateUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form UpdateUsuario
     */
    public UpdateUsuario() {
        initComponents();
        panelInf.setVisible(false);
        btnCancelar.setVisible(false);

    }

    private String senha, senhaAntiga;

    public boolean acharUmUsuario(String valor) {

        UsuarioDAO uDao = new UsuarioDAO();
        Usuario u = uDao.umUsuario(valor);
        if (u.getId() != 0) {
            lblNomeUser.setText(u.getNome());
            txtUser.setText(u.getUsuario());
            senhaAntiga = u.getSenha();
            return true;
        } else {

        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscaID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        panelInf = new javax.swing.JPanel();
        lblN = new javax.swing.JLabel();
        lblNomeUser = new javax.swing.JLabel();
        lblU = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblU1 = new javax.swing.JLabel();
        lblU2 = new javax.swing.JLabel();
        txtSenhaAntiga = new javax.swing.JPasswordField();
        txtSenhaNova = new javax.swing.JPasswordField();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alterar Usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        txtBuscaID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscaIDKeyReleased(evt);
            }
        });

        jLabel1.setText("ID Usuário:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblN.setText("Nome:");

        lblNomeUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblU.setText("User:");

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblU1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblU1.setText("Senha antiga:");

        lblU2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblU2.setText("Senha nova:");

        btnSalvar.setText("Salvar Alteração");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfLayout = new javax.swing.GroupLayout(panelInf);
        panelInf.setLayout(panelInfLayout);
        panelInfLayout.setHorizontalGroup(
            panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfLayout.createSequentialGroup()
                .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelInfLayout.createSequentialGroup()
                                .addComponent(lblU1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenhaAntiga))
                            .addGroup(panelInfLayout.createSequentialGroup()
                                .addComponent(lblU2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelInfLayout.createSequentialGroup()
                                .addComponent(lblU)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUser))))
                    .addGroup(panelInfLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNomeUser)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        panelInfLayout.setVerticalGroup(
            panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeUser)
                    .addComponent(lblN))
                .addGap(26, 26, 26)
                .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblU)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblU1)
                    .addComponent(txtSenhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblU2)
                    .addComponent(txtSenhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Pode alterar usuário e senha nesta janela.");

        btnCancelar.setText("Outro usuário?");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtBuscaID, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(btnBuscar))
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addGap(5, 5, 5)
                .addComponent(panelInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        if (txtBuscaID.getText().matches("[0-9]+")) {
            if (acharUmUsuario(txtBuscaID.getText())) {
                panelInf.setVisible(true);
                btnBuscar.setEnabled(false);
                btnCancelar.setVisible(true);
                txtBuscaID.setEnabled(false);
            } else {
                txtBuscaID.setEnabled(true);
                panelInf.setVisible(false);
            }
        } else {
            panelInf.setVisible(false);
            JOptionPane.showMessageDialog(null, "Insira um ID válido.");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (((txtBuscaID.getText().equals("") || txtUser.getText().equals("")) || txtSenhaAntiga.getText().equals("")) || txtSenhaNova.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
        } else {

            senha = txtSenhaAntiga.getText();

            if (senha.equals(senhaAntiga)) {
                UsuarioDAO uDao = new UsuarioDAO();
                Usuario novoUsuario = new Usuario();
                novoUsuario.setId(Integer.parseInt(txtBuscaID.getText()));
                novoUsuario.setUsuario(txtUser.getText());
                novoUsuario.setSenha(txtSenhaNova.getText());
                uDao.update(novoUsuario);

                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Senha antiga errada.");
            }
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtBuscaIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscaIDKeyReleased
        if (txtBuscaID.getText().equals("")) {
            panelInf.setVisible(false);
            lblNomeUser.setText("");
            txtSenhaAntiga.setText("");
            txtSenhaNova.setText("");
        }
    }//GEN-LAST:event_txtBuscaIDKeyReleased

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        txtBuscaID.setText("");
        txtBuscaID.setEnabled(true);
        btnCancelar.setVisible(false);
        btnBuscar.setEnabled(true);
        panelInf.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblNomeUser;
    private javax.swing.JLabel lblU;
    private javax.swing.JLabel lblU1;
    private javax.swing.JLabel lblU2;
    private javax.swing.JPanel panelInf;
    private javax.swing.JTextField txtBuscaID;
    private javax.swing.JPasswordField txtSenhaAntiga;
    private javax.swing.JPasswordField txtSenhaNova;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
